development:
  adapter: postgresql
  encoding: unicode
  database: blog
  pool: 5
  username: antti
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: blog
  pool: 5
  username: antti
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: blog
  pool: 5
  username: antti
  password:
